## Provide custom recording or alerting rules to be deployed into the cluster.
additionalPrometheusRules:
  - name: kubernetes-apps
    groups:
      - name: kubernetes-apps
        rules:
        - alert: KubePodCrashLooping-System
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
              }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
          expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",
            namespace=~"[% system_namespaces_regex %]"}[15m]) * 60 * 5 > 0
          for: 15m
          labels:
            severity: critical
            label_example_com_ci_monitoring: [% ci_cluster_id %]
        - alert: KubePodCrashLooping
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
              }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
          expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",
            namespace!~"[% system_namespaces_regex %]"}[15m]) * 60 * 5 > 0
          for: 15m
          labels:
            severity: critical
