apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  namespace: default
spec:
  replicas: 2
  terminationGracePeriodSeconds: 30
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: spring-boot
          image: 910058517622.dkr.ecr.ap-northeast-2.amazonaws.com/zionex-ecr:demo
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-info
                  key: db-host
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: spring-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: password
