name: create-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: test
        run: |
          echo ${{ github.ref }} > Release.txt
          echo ${{ github.sha }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: create-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: test2
        run: |
          echo ${{ github.ref }}
          echo ${{ steps.create-tag.outputs.new_tag }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: Release.txt
          tag_name: ${{ steps.create-tag.outputs.new_tag }}
